# Chatbot API settings
server.port=8081

# Azure OpenAI
azure.openai.endpoint=${AZURE_OPENAI_ENDPOINT}
azure.openai.api.key=${AZURE_OPENAI_API_KEY}
azure.openai.deployment=gpt-4o

# Azure AI Search
azure.search.api.key=${AZURE_SEARCH_API_KEY}
azure.search.endpoint=${AZURE_SEARCH_ENDPOINT}
azure.search.index=${AZURE_SEARCH_INDEX}
azure.search.index.semantic.configuration=${AZURE_SEARCH_SEMANTIC_CONFIG}

# Oracle DB
oracle.db.url=${ORACLE_DB_URL}
oracle.db.username=${ORACLE_DB_USERNAME}
oracle.db.password=${ORACLE_DB_PASSWORD}

logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.apache.http=DEBUG

# PDF QA settings
pdfqa.enabled=true
pdfqa.localDir=./
pdfqa.search.indexName=pdfqa-index
pdfqa.search.topK=8
pdfqa.openai.embeddingDeployment=text-embedding-3-large
pdfqa.search.bootstrap=true
pdfqa.extract.maxPagesPerDoc=200
pdfqa.answer.mode=extractive

# Swagger / OpenAPI
springdoc.swagger-ui.operationsSorter=method
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Azure SQL
spring.datasource.url=${AZURE_SQL_URL}
spring.datasource.username=${AZURE_SQL_USERNAME}
spring.datasource.password=${AZURE_SQL_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Logging
logging.level.root=INFO
logging.level.com.example=DEBUG
logging.level.org.springframework=INFO

acs.numOfRecents=10
